### ISSUE TITLE
Count of total matches is incorrect when cpo-c is not present

### ISSUE THREAD

**Issue by JoshMermel** [google/vim-searchindex#10] opened 2016-01-11 22:07 UTC
repro instructions:
- :set cpoptions-=c
- 5iab<esc>
- /abab
- N

observe the count reads [4/2] rather than [4/4]

**Comment by rburny** [comment] 2016-01-11 22:59
I've looked into that and it seems like there's no way to get `[4/4]` result. The problem is that `vim-searchindex` uses `:%s/pattern//n` Ex command internally, and this command does not provide appropriate option. But this is also the only search command that works efficiently on large line ranges, so it cannot be replaced.

I can however implement a partial fix, which will at least make numbers self-consistent. I could make all match counts work as if `cpoptions` contained `c`. This means that search counts will be inconsistent with cursor jumps, displaying `[2/2]` in your case - which still makes more sense than `[4/2]`.

What do you think?  Sorry that there's no better fix, but Vim's searching functions are a mess, and much of complexity in `vim-searchindex` is working around their quirks.

**Comment by JoshMermel** [comment] 2016-01-12 14:30
Hmm, would it be sensible to file an upstream feature request with Ex?

I slightly prefer `[4/2]` to `[2/2]` as the result of the above instructions. If we used `nnn` instead of `N`, I think it is better to have the first number increment with each press.

Also in practice I don't think `cpo-c` has ever made a difference in my Vim usage. I suspect very few users will ever come across this bug unless they contrive a situation to check for it like I did.

**Comment by rburny** [comment] 2016-01-12 16:28
Vim is a fragile legacy codebase (still written in pre-ANSI C), and does not have maintainers to implement such feature requests. So, I don't consider changing it a realistic option.

Since we can't solve this problem, I can show you another fun thing in exchange:

```
set shortmess+=s
/some_non_existing_text<CR>
```

Now error message is two-line long, requiring you to press enter. Why does it happen, given that "shortmess+=s" is pretty much unrelated? I have no idea, but it's yet another reason not to touch this codebase :)

**Closed as completed by rburny** 2016-01-12 16:28 UTC
