### ISSUE TITLE
Search index not shown when first complete a search with incsearch.vim

### ISSUE THREAD

**Issue by kminh** [google/vim-searchindex#9] opened 2015-11-30 22:40 UTC
Hello again,

I just notice an issue when using vim-searchindex with incsearch.vim: when you search for something using `/` the index is not shown after pressing enter. All that is shown after pressing enter is `/`, if searchindex is not active, `/pattern` is shown.

Hopefully this can be fixed, thank you.

**Comment by rburny** [comment] 2015-12-01 17:57
Yes, this is a known issue, which I've already discussed in https://github.com/google/vim-searchindex/issues/6#issuecomment-149567007

The problem is that `incsearch` uses fake command line, instead of Vim's native one. Therefore, `vim-searchindex` has no way of detecting when the search command is issued. Last time I looked at that, there was no way to plug into this simulated command line, but you can ask @haya14busa - maybe he can advise something or maybe he could implement a small extension mechanism.

**Comment by kminh** [comment] 2015-12-02 07:51
There's a `IncSearchExecute` user event, can that be of any help?

Also I just found this: https://github.com/haya14busa/incsearch-index.vim . It seems like hooking into incsearch.vim is already possible, not sure if it's easy to do though.

**Comment by rburny** [comment] 2015-12-02 11:31
OK, I've tried doing the obvious thing:

```
autocmd User IncSearchExecute :SearchIndex
```

and it doesn't work. I see the search counts displayed briefly, but they're immediately overwritten. At this point, I claim it is a problem with `incsearch` plugin - it shouldn't cover the message printed from autocmd, since this autocmd is logically executed _after_ search.

Please file a bug against `incsearch`. I don't use it myself, so I don't really want to invest too much time into investigating this.

**Comment by rburny** [comment] 2017-04-09 15:53
I'll close it as not feasible, since the problem lies in `incsearch.vim`, not `vim-searchindex`.

**Closed as completed** 2017-04-09 15:52 UTC
