### ISSUE TITLE
Exchange the position of index and pattern

### ISSUE THREAD

**Issue by kminh** [google/vim-searchindex#8] opened 2015-11-26 08:23 UTC
Hello, thank you for this useful plugin.

Does it make sense to print matches like this:

```
/<pattern here> (1 of n)
```

instead of:

```
[1/n] /<pattern here>
```

I'm using this plugin with https://github.com/haya14busa/incsearch.vim and the matches seem to flicker a lot when using the current display, maybe because it has to switch from `/<pattern here>` to `[1/n] /<pattern here>`.

I believe `/<pattern here> (1 of n)` is more consistent with how Vim works right now, for example the quickfix list is using this: `qf (1 of n)`.

**Comment by rburny** [comment] 2015-11-27 12:10
Let's first try to diagnose the flickering cause. Can you explain how to reproduce this? In particular:
- what mappings do you have (AFAIU incsearch doesn't do anything without user adding mappings).
- when does the flickering appear; what keys are you pressing?

**Comment by kminh** [comment] 2015-11-27 14:51
I could reproduce the issue using a minimal vim setup (require vim-plug):

``` vim
set nocompatible

call plug#begin('~/dotfiles/.vim/bundle')

Plug 'google/vim-searchindex'
Plug 'haya14busa/incsearch.vim'

call plug#end()

syntax on
set relativenumber
set ignorecase
set smartcase
set incsearch
set showmatch
set hlsearch

" integration with incsearch.vim
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)

map n  <Plug>(incsearch-nohl-n)<Plug>SearchIndex
map N  <Plug>(incsearch-nohl-N)<Plug>SearchIndex
```

I tried to create a screencast but whenever I recorded the flickering didn't happen continuously, weird. Here it is anyway:

![incsearch-searchindex-flickering-2015-11-27_21 31 43](https://cloud.githubusercontent.com/assets/6402124/11443417/9fb3cfb6-954f-11e5-8d1b-d9aa08694df2.gif)

The key here is to have `syntax on`, `set relativenumber` and `set ft=(anything)`. The demo file in the screencast is trivial but it will flicker more in a syntax-heavy file.

Also, in the above screencast I hold down the `n` button at the end, you can also see the "Search hit BOTTOM" message too, but I guess it's not possible to remove it.

**Comment by rburny** [comment] 2015-11-27 23:50
Thanks for the detailed report! The flickering that you noticed is unrelated to `incsearch`; it was a bug introduced to my plugin in one of the recent commits. It should be fixed now.
Also, `"search hit BOTTOM"` messages can be disabled with `:set shortmess+=s`.

However, there is one more issue with your setup - your remappings for `n` and `N` will not work. This is because Vim loads plugins after `.vimrc`, and mappings done by plugins override ones from `.vimrc`. Since `vim-searchindex` remaps `n` and `N`, it will overwrite your mappings. I should fix this, I just need to think of a best way to do that. Until it's done, you can force your settings with `autocmd` (just remember to use `<silent>`):

```
autocmd VimEnter *
  \ map <silent> n <Plug>(incsearch-nohl-n)<Plug>SearchIndex
autocmd VimEnter *
  \ map <silent> N <Plug>(incsearch-nohl-N)<Plug>SearchIndex
```

**Closed as completed** 2015-11-27 23:50 UTC

**Comment by kminh** [comment] 2015-11-28 00:07
Thank you for looking into this!

Actually in my vimrc I'm using the `VimEnter` autocmd to define the mappings. The best way to fix is to use `hasmapto()` and possibly `maparg()` I think.

Btw, is it possible to add support for customized output format? Like I proposed above: `/pattern (1 of n)` instead of `[1/n] /pattern`?

Either way, this is the best search index plugin I've come across, please keep up the good work.

**Comment by rburny** [comment] 2015-11-29 23:35
It's simple from the technical standpoint, I just don't understand why would it be preferable (and I also don't want to introduce flags and knobs for every little thing). With the counts printed on the left side, they're always in the same position, regardless of the search pattern length. This makes them easier to quickly glance at, and they don't visually blend with the pattern.

When I use `grep` in Vim with default settings (`vim -u NONE`), I get this message:

```
"searchindex.txt" 69 lines, 3112 characters
(1 of 57): *searchindex.txt*  Display current & total number of search matches
```

Hence, I believe printing counts on the left is both more practical and consistent with Vim.

And "(1 of n)" looks nicer than "[1/n]", but I'm not sure if changing it is worth the annoyance.

**Comment by kminh** [comment] 2015-11-30 05:01
IMO the display of the count is not a little thing, it's a thing that affects user experience (for e.g. right now we both have different opinions).

I hope you will reconsider though :)
